# dbt_project.yml
name: 'mds'
version: '1.0.0'
config-version: 2


profile: 'mds'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  mds:
    # This configuration applies to everything in models/staging/
    staging:
      +materialized: view
      +schema: MICROMOBILITY_STAGING
    
    # This configuration applies to everything in models/marts/
    marts:
      +materialized: table
      +schema: MICROMOBILITY_ANALYTICS

      # dbt_project.yml

quoting:
  database: true
  schema: true
  identifier: true

seeds:
  mds:                  
    +schema: MICROMOBILITY_STAGING
    +quote_columns: true