voi_mds:
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('PG_HOST') }}"
      user: "{{ env_var('PG_USER') }}"
      password: "{{ env_var('PG_PASS') }}"
      dbname: "{{ env_var('PG_DATABASE') }}"
      schema: public
      port: 5432  # No quotes, no braces, just the number
      threads: 4  # No quotes, just the number
  target: dev