version: 2

sources:
  - name: raw_mds
    database: stage_micromobility
    schema: MICROMOBILITY_RAW
    tables:
      # --- VOI TABLES ---
      - name: VOI_VEHICLES
      - name: VOI_TRIPS
      - name: VOI_VEHICLES_STATUS
      - name: VOI_EVENTS

      # --- DOTT TABLES ---
      - name: DOTT_VEHICLES
      - name: DOTT_TRIPS
      - name: DOTT_VEHICLES_STATUS
      - name: DOTT_EVENTS          
      - name: DOTT_TELEMETRY       
      - name: DOTT_STATUS_CHANGES   

      # --- BOLT TABLES ---
      - name: BOLT_VEHICLES
      - name: BOLT_EVENTS
      - name: BOLT_TRIPS
      - name: BOLT_STATUS_CHANGES   

      # --- POPPY TABLES ---
      - name: POPPY_TRIPS
      - name: POPPY_FREE_BIKE_STATUS
      - name: POPPY_VEHICLE_TYPES
      - name: POPPY_GEOFENCING_ZONES
      - name: POPPY_SYSTEM_INFORMATION
      - name: POPPY_SYSTEM_PRICING_PLANS