version: 2

seeds:
  - name: voi_lost_vehicles
    columns:
      - name: TRIP_ID
        quote: true
        tests:
          - unique
          - not_null
  - name: dott_lost_vehicles
    columns:
      - name: TRIP_ID
        quote: true
        tests:
          - unique
          - not_null
  - name: bolt_lost_vehicles
    columns:
      - name: TRIP_ID
        quote: true
        tests:
          - unique
          - not_null